### ISSUE TITLE
KeyError: 'MultiGammaLrUpdaterHook is not in the hook registry'

### ISSUE THREAD

**Issue by Qjizhi** [facebookresearch/CODD#1]
First thanks for your great work! It seems `MultiGamma` is not supported by mmcv. When I use `schedule_stereo_finetune.py`, where the lr_config is `OneCycle`, the training is ok, but the visualization performance is not good.

**Comment by mli0603** [comment]
Hi @Qjizhi, thank you for your interest in the project.

I will look into this. I think the customized LR scheduler may have been stripped off during the code clean up. I will let you know once it is fixed.

**Comment by Qjizhi** [comment]
> 
Sounds great, thanks!


> Hi @Qjizhi, thank you for your interest in the project.
> 
> I will look into this. I think the customized LR scheduler may have been stripped off during the code clean up. I will let you know once it is fixed.

**Comment by Qjizhi** [comment]
> Hi @Qjizhi, thank you for your interest in the project.
> 
> I will look into this. I think the customized LR scheduler may have been stripped off during the code clean up. I will let you know once it is fixed.

I tried some supported `lr_config` in https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py#L9, However, the model seems doesn't converge.

**Comment by ywwwer** [comment]
@Qjizhi I added this customized hook back in the latest commit

**Comment by Qjizhi** [comment]
awsome, thanks! @ywwwer 

> @Qjizhi I added this customized hook back in the latest commit

**Comment by mli0603** [comment]
fixed by PR #2
